# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meingui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hauptfenster(object):
    def setupUi(self, Hauptfenster):
        Hauptfenster.setObjectName("Hauptfenster")
        Hauptfenster.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Hauptfenster)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")
        Hauptfenster.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hauptfenster)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Hauptfenster.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hauptfenster)
        self.statusbar.setObjectName("statusbar")
        Hauptfenster.setStatusBar(self.statusbar)

        self.retranslateUi(Hauptfenster)
        self.pushButton.clicked.connect(Hauptfenster.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Hauptfenster)

    def retranslateUi(self, Hauptfenster):
        _translate = QtCore.QCoreApplication.translate
        Hauptfenster.setWindowTitle(_translate("Hauptfenster", "MainWindow"))
        self.pushButton.setText(_translate("Hauptfenster", "Beenden"))
